---
name: Lint Code Base
on:
  workflow_call:

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v6.5.1 # x-release-please-version
        env:
          DEFAULT_BRANCH: main
          VALIDATE_KUBERNETES_KUBECONFORM: false
          VALIDATE_RUST_2015: false
          VALIDATE_RUST_2018: false
          VALIDATE_RUST_2021: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
